# site settings
title: Jake
subtitle: Roller
email:
description: I'm passionate about rocketry and space systems and am currently working at Astra doing avionics test engineering for in-space propulsion. I graduated from Worcester Polytechnic Institute in March 2023 with a degree in Aerospace Engineering focusing on Astronautical Engineering and a minor in Electrical Engineering. Browse through each project to learn more!
baseurl:  # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Jake Roller
street_address:
city:
state:
zip_code:
country:
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 9

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub:
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn: https://www.linkedin.com/in/jakeroller
  Twitter:
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md
